# Generated by Django 5.0.1 on 2024-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearsExperience', models.FloatField()),
                ('Salary', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
